version: '3.1'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    ports:
      - 10081:80
    volumes:
      - ~/var/gitlab/etc:/etc/gitlab
      - ~/var/gitlab/opt:/var/opt/gitlab
      - ~/var/gitlab/log:/var/log/gitlab

